version: '3.1'
services:
  appstaging:
    container_name: vaadin-crm-staging
    image: odsoft-image
    build: ./
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgresqlcrmstaging
      - DB_PORT=5432
    depends_on:
      - postgresqlcrmstaging
  postgresqlcrmstaging:
    container_name: postgresqlcrmstaging
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=odsoft