version: '3.1'
services:
  app:
    container_name: vaadin-crm
    image: odsoft-image
    build: ./
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgresqlcrm
      - DB_PORT=5432
    depends_on:
      - postgresqlcrm
  postgresqlcrm:
    container_name: postgresqlcrm
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=odsoft
    volumes:
      - "odsoft_data:/var/lib/postgresql/data"
volumes:
  odsoft_data: